### ISSUE TITLE
Unclear instructions

### ISSUE THREAD

**Issue by keeganjk** [notthebee/revertcoreboot#2]
Is one literally supposed to put `laptop=force_I_want_a_brick`, or is that a placeholder? What does this do? I assume when it says "Backup the old content and put it on an external storage:", it actually means to do that with regard to the previous step, and then do the next step?

**Comment by keeganjk** [comment]
Never mind, upon looking in the `flashrom` manual, this appears to be an actual (not advised) thing.

**Comment by keeganjk** [comment]
Okay, I followed all the steps verbatim, it did end up booting and it looked like the old one, but it took a lot longer to boot [at least, the first time – seems better the second time]. Perhaps it just seemed that way because Coreboot is much smaller and faster.

**Comment by kayodde** [comment]
How did you bypass the SPI configuration locked down thing?
